image: docker:latest

services:
  - docker:dind
stages:
  - build
#   - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE:latest .
    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

# deploy:
#   stage: deploy
#   only:
#     - master
#   script:
#     - docker-compose down
#     - docker-compose build --no-cache
#     - docker-compose up -d